/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "checkSyntaxTests.check" instead.
 */

#include <check.h>

#line 1 "checkSyntaxTests.check"
#include "checkSyntax.h"

START_TEST(is_I_X_C_test)
{
#line 4
	fail_unless(is_I_X_C('I') == 1, "is_I_X_C failed - output false for good input");
	fail_unless(is_I_X_C('X') == 1, "is_I_X_C failed - output false for good input");
	fail_unless(is_I_X_C('C') == 1, "is_I_X_C failed - output false for good input");
	fail_unless(is_I_X_C('i') == 0, "is_I_X_C failed - output true for bad input");
	fail_unless(is_I_X_C('M') == 0, "is_I_X_C failed - output true for bad input");

}
END_TEST

START_TEST(is_V_L_D_M_test)
{
#line 11
	fail_unless(is_V_L_D_M('V') == 1, "is_V_L_D_M failed - output false for good input");
	fail_unless(is_V_L_D_M('L') == 1, "is_V_L_D_M failed - output false for good input");
	fail_unless(is_V_L_D_M('D') == 1, "is_V_L_D_M failed - output false for good input");
	fail_unless(is_V_L_D_M('M') == 1, "is_V_L_D_M failed - output false for good input");
	fail_unless(is_V_L_D_M('v') == 0, "is_V_L_D_M failed - output true for bad input");
	fail_unless(is_V_L_D_M('l') == 0, "is_V_L_D_M failed - output true for bad input");
	fail_unless(is_V_L_D_M('_') == 0, "is_V_L_D_M failed - output true for bad input");

}
END_TEST

START_TEST(maxLetterCountTest)
{
#line 20
	fail_unless(maxLetterCount('I') == 3, "maxLetterCountFailes - output something other than 3 for I");
	fail_unless(maxLetterCount('X') == 3, "maxLetterCountFailes - output something other than 3 for X");
	fail_unless(maxLetterCount('C') == 3, "maxLetterCountFailes - output something other than 3 for C");
	fail_unless(maxLetterCount('M') == 3, "maxLetterCountFailes - output something other than 3 for M");
	fail_unless(maxLetterCount('V') == 1, "maxLetterCountFailes - output something other than 1 for V");
	fail_unless(maxLetterCount('L') == 1, "maxLetterCountFailes - output something other than 1 for L");
	fail_unless(maxLetterCount('D') == 1, "maxLetterCountFailes - output something other than 1 for D");
	
}
END_TEST

START_TEST(maxLengthExceededTest)
{
#line 29
	fail_unless(maxLengthExceeded("MMXVD") == 0, "maxLengthExceeded - output true for MMXVD");
	fail_unless(maxLengthExceeded("M") == 0, "maxLengthExceeded - output true for MMXVD");
	fail_unless(maxLengthExceeded("MMMXIV") == 0, "maxLengthExceeded - output true for MMXVD");
	fail_unless(maxLengthExceeded("") == 0, "maxLengthExceeded - output true for MMXVD");
	fail_unless(maxLengthExceeded("This_String_Will_Fail") == 1, "maxLengthExceeded - output false for long string");
	fail_unless(maxLengthExceeded("StringWill_Pass") == 0, "maxLengthExceeded - output true for MMXVD");
	
	
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, is_I_X_C_test);
    tcase_add_test(tc1_1, is_V_L_D_M_test);
    tcase_add_test(tc1_1, maxLetterCountTest);
    tcase_add_test(tc1_1, maxLengthExceededTest);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
