/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "convertTests.check" instead.
 */

#include <check.h>

#line 1 "convertTests.check"
#include "convert.h"

START_TEST(convertFromRomanNumeralToBaseTenTest)
{
#line 4
	fail_unless(convertFromRomanNumeralToBaseTen("I") == 1,"Failed to convert I to 1");
	fail_unless(convertFromRomanNumeralToBaseTen("V") == 5,"Failed to convert V to 5");
	fail_unless(convertFromRomanNumeralToBaseTen("X") == 10,"Failed to convert X to 10");
	fail_unless(convertFromRomanNumeralToBaseTen("L") == 50,"Failed to convert L to 50");
	fail_unless(convertFromRomanNumeralToBaseTen("C") == 100,"Failed to convert C to 100");
	fail_unless(convertFromRomanNumeralToBaseTen("D") == 500,"Failed to convert D to 500");
	fail_unless(convertFromRomanNumeralToBaseTen("M") == 1000,"Failed to convert M to 1000");
	
}
END_TEST

START_TEST(lookAheadTest)
{
#line 13
	int *index1 = 0;
	fail_unless(lookAhead(&index1, "M") == 1000,"Failed to return value of M");

}
END_TEST

START_TEST(pairValueTest)
{
#line 17
	fail_unless(pairValue('I', 'V') == 4,"Failed to return value of M");
	
}
END_TEST

START_TEST(legalPairTest)
{
#line 20
	fail_unless(legalPair('I', 'V') == 1,"Failed to return true for legal pair IV");
	fail_unless(legalPair('I', 'X') == 1,"Failed to return true for legal pair IX");
	fail_unless(legalPair('X', 'L') == 1,"Failed to return true for legal pair XL");
	fail_unless(legalPair('X', 'C') == 1,"Failed to return true for legal pair XC");
	fail_unless(legalPair('C', 'D') == 1,"Failed to return true for legal pair CD");
	fail_unless(legalPair('C', 'M') == 1,"Failed to return true for legal pair CM");
	fail_unless(legalPair('M', 'M') == 1,"Failed to return true for legal pair MM");
	fail_unless(legalPair('I', 'M') == 0,"Failed to return false for illegal pair CM");
	fail_unless(legalPair('X', 'M') == 0,"Failed to return false for illegal pair CM");
	
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, convertFromRomanNumeralToBaseTenTest);
    tcase_add_test(tc1_1, lookAheadTest);
    tcase_add_test(tc1_1, pairValueTest);
    tcase_add_test(tc1_1, legalPairTest);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
