/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "convertTests.check" instead.
 */

#include <check.h>

#line 1 "convertTests.check"
#include "convert.h"

START_TEST(convertFromRomanNumeralToBaseTenTest)
{
#line 4
	fail_unless(convertFromRomanNumeralToBaseTen("I") == 1,"Failed to convert I to 1");
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, convertFromRomanNumeralToBaseTenTest);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
