/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "romanErrorTests.check" instead.
 */

#include <check.h>

#line 1 "romanErrorTests.check"
#include <stdlib.h>
#include <stdio.h>
#include "romanError.h"

START_TEST(badInput)
{
#line 6
	ck_assert(showMessage(0) == NULL);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, badInput);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
