/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "romanErrorTests.check" instead.
 */

#include <check.h>

#line 1 "romanErrorTests.check"
#include <stdlib.h>
#include <stdio.h>
#include "romanError.h"
#include "convert.h"
#include <sys/stat.h>


START_TEST(badRomanNumeralCharacter)
{
#line 9
	fail_unless(convertSingleCharacterToInt('J') == -1, "Conversion of non Roman Numeral to int test failed");
	//now test for lookAhead since it uses the character conversion
	
}
END_TEST

START_TEST(badlookAheadPairs)
{
#line 13
	int index = 0;
	ck_assert_msg(lookAhead('J', '%', &index) == -1, "Conversion of non Roman Numeral to int test failed (lookAhead)");
	ck_assert_msg(lookAhead('I', 'F', &index) == -1, "Conversion of non Roman Numeral to int test failed (lookAhead)");
	ck_assert_msg(lookAhead('^', 'V', &index) == -1, "Conversion of non Roman Numeral to int test failed (lookAhead)");
	
	
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, badRomanNumeralCharacter);
    tcase_add_test(tc1_1, badlookAheadPairs);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
